apiVersion: v2
name: traefik
description: A Weaveworks Helm chart for the traefik proxy
type: application
version: 0.0.1
dependencies:
  - name: traefik
    version: "20.2.0"
    repository: "https://traefik.github.io/charts"
kubeVersion: ">=1.16.0-0"
sources:
  - https://github.com/traefik/traefik-helm-chart

keywords:
- ingress

maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": traefik
  "weave.works/category": ingress
  "weave.works/layer": layer-2
  "weave.works/operator": "true"
