external-dns:
  rbac:
    create: true
  txtOwnerId: '{{ or (.params).CLUSTER_NAME "test-cluster" }}'
  serviceAccount:
    name: external-dns
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::482649550366:role/{{ or (.params).CLUSTER_NAME "test-cluster" }}-external-dns
