extraManifests:
- apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
  kind: Kustomization
  metadata:
    name: app-secrets
    namespace: flux-system
  spec:
    decryption:
      provider: sops
      secretRef:
        name: sops-gpg
    force: false
    interval: 5m0s
    path: ./apps/traefik-hub
    prune: true
    sourceRef:
      kind: GitRepository
      name: flux-system
hub-agent:
  tokenSecretRef:
    name: hub-token
    key: token