cert-manager:
  installCRDs: true
  serviceAccount:
    name: cert-manager
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::482649550366:role/{{ .params.CLUSTER_NAME }}-cert-manager"
         
